extensions: [cpp, c, h, hpp]

keywords:
  keyword:
    - regex: "\\b(char|class|const|double|enum|explicit|friend|inline|int|long|namespace|operator|private|protected|public|short|signals|signed|slots|static|struct|template|typedef|typename|union|unsigned|virtual|void|volatile|foreach)\\b"
      color: "#003478"
      bold: "true"
    - regex: "\\b(for|while|do|if|else)\\b"
      color: "#D9001D"
    - regex: "(?<!\\w)#include(?!\\w)"
      color: "#800080"
  comment:
    - regex: "//[^\n]*"
      color: "#336934"
      italic: "true"
  string:
    - regex: "\"(\\\\.|[^\"\\\\])*\""
      color: "#E37100"
    - regex: "\\\\"
      color: "#FFDE00"
  number:
    - regex: "\\b\\d+\\b"
      color: "#0000FF"
  parenthesis:
    - regex: "[()]"
      color: "#6495ED"
  function:
    - regex: "\\b(?!for\\b|if\\b|else\\b|while\\b|do\\b)[a-zA-Z_][a-zA-Z0-9_]*(?=\\s*\\()"
      color: "#DBA800"
  qualifiedName:
    - regex: "\\b\\w+(?=\\s*::)"
      color: "#309676"
